{% set name = "pycld2" %}
{% set version = "0.42" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycld2-{{ version }}.tar.gz
  sha256: 5188084c97f99e896cf464057c64f6b0f91f68d111182dceb5bcfe487d7f4c0f
  patches:
    - relative_sources.patch

build:
  number: 0
  skip: true  # [win, python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - pycld2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aboSamoor/pycld2
  summary: Python bindings around Google Chromium's embedded compact language detection library (CLD2)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - d-cunningham
    - JennaLipscomb
    - AdMax18
